# Generated by Django 4.2.23 on 2025-09-24 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=20)),
                ('humidity', models.CharField(choices=[('low', 'Low humidity'), ('normal', 'Normal'), ('high', 'High humidity')], default='normal', max_length=20)),
                ('sunlight_exposure', models.CharField(choices=[('full_sun', 'Full Sun'), ('partial_sun', 'Partial Sun'), ('indirect_sun', 'Indirect Sunlight'), ('full_shade', 'Full Shade')], default='partial_sun', max_length=20)),
                ('air', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_level', models.CharField(blank=True, max_length=50, null=True)),
                ('cones', models.CharField(blank=True, max_length=255, null=True)),
                ('cuisine', models.CharField(blank=True, max_length=255, null=True)),
                ('cycle', models.CharField(blank=True, max_length=50, null=True)),
                ('drought_tolerant', models.CharField(blank=True, max_length=10, null=True)),
                ('edible_fruit', models.CharField(blank=True, max_length=255, null=True)),
                ('edible_leaf', models.CharField(blank=True, max_length=255, null=True)),
                ('flowering_season', models.CharField(blank=True, max_length=255, null=True)),
                ('flowers', models.CharField(blank=True, max_length=255, null=True)),
                ('fruiting_season', models.CharField(blank=True, max_length=255, null=True)),
                ('fruits', models.CharField(blank=True, max_length=255, null=True)),
                ('growth_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('harvest_method', models.CharField(blank=True, max_length=255, null=True)),
                ('harvest_season', models.CharField(blank=True, max_length=255, null=True)),
                ('indoor', models.CharField(blank=True, max_length=10, null=True)),
                ('invasive', models.CharField(blank=True, max_length=10, null=True)),
                ('leaf', models.CharField(blank=True, max_length=10, null=True)),
                ('maintenance', models.CharField(blank=True, max_length=255, null=True)),
                ('medicinal', models.CharField(blank=True, max_length=255, null=True)),
                ('pest_susceptibility', models.CharField(blank=True, max_length=255, null=True)),
                ('poisonous_to_humans', models.CharField(blank=True, max_length=10, null=True)),
                ('poisonous_to_pets', models.CharField(blank=True, max_length=10, null=True)),
                ('pruning_month', models.CharField(blank=True, max_length=50, null=True)),
                ('rare', models.CharField(blank=True, max_length=10, null=True)),
                ('salt_tolerant', models.CharField(blank=True, max_length=10, null=True)),
                ('soil', models.CharField(blank=True, max_length=255, null=True)),
                ('sunlight', models.TextField(blank=True, null=True)),
                ('thorny', models.CharField(blank=True, max_length=10, null=True)),
                ('tropical', models.CharField(blank=True, max_length=10, null=True)),
                ('watering', models.CharField(blank=True, max_length=50, null=True)),
                ('sun', models.CharField(blank=True, max_length=50, null=True)),
                ('edible', models.CharField(blank=True, max_length=10, null=True)),
                ('hardiness', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('watering_long', models.TextField(blank=True, null=True)),
                ('pruning', models.TextField(blank=True, null=True)),
                ('watering_period', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('last_watered_date', models.DateField(blank=True, null=True)),
                ('last_fertilized_date', models.DateField(blank=True, null=True)),
                ('last_pruning_date', models.DateField(blank=True, null=True)),
                ('last_rotating_date', models.DateField(blank=True, null=True)),
                ('last_spraying_date', models.DateField(blank=True, null=True)),
                ('isWateringReminder', models.BooleanField(default=True)),
                ('isPruningReminder', models.BooleanField(default=True)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('age', models.CharField(blank=True, choices=[('less_1_year', 'Less than 1 year'), ('2_3_years', '2-3 years'), ('more_3_years', 'More than 3 years')], max_length=20, null=True)),
                ('pruning_time', models.PositiveIntegerField(blank=True, null=True)),
                ('pruning_time_unit', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10, null=True)),
                ('sprayed_time', models.PositiveIntegerField(blank=True, null=True)),
                ('sprayed_unit', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10, null=True)),
                ('rotation_time', models.PositiveIntegerField(blank=True, null=True)),
                ('rotation_unit', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10, null=True)),
                ('pot_type', models.CharField(blank=True, choices=[('clay', 'Clay'), ('plastic', 'Plastic'), ('glazed_ceramic', 'Glazed ceramic/porcelain pot'), ('cement', 'Cement'), ('peat', 'Peat'), ('stone', 'Stone'), ('wood', 'Wood'), ('fabric', 'Fabric')], max_length=30, null=True)),
                ('pot_size', models.CharField(blank=True, max_length=50, null=True)),
                ('drainage', models.CharField(blank=True, choices=[('with_holes', 'With holes'), ('without_holes', 'Without holes')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_plants', to='api.garden')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plant', to='api.plantinfo')),
            ],
        ),
    ]
