# Generated by Django 5.2.4 on 2025-08-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_level', models.CharField(blank=True, max_length=50, null=True)),
                ('cones', models.CharField(blank=True, max_length=255, null=True)),
                ('cuisine', models.CharField(blank=True, max_length=255, null=True)),
                ('cycle', models.CharField(blank=True, max_length=50, null=True)),
                ('drought_tolerant', models.CharField(blank=True, max_length=10, null=True)),
                ('edible_fruit', models.CharField(blank=True, max_length=255, null=True)),
                ('edible_leaf', models.CharField(blank=True, max_length=255, null=True)),
                ('flowering_season', models.CharField(blank=True, max_length=255, null=True)),
                ('flowers', models.CharField(blank=True, max_length=255, null=True)),
                ('fruiting_season', models.CharField(blank=True, max_length=255, null=True)),
                ('fruits', models.CharField(blank=True, max_length=255, null=True)),
                ('growth_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('harvest_method', models.CharField(blank=True, max_length=255, null=True)),
                ('harvest_season', models.CharField(blank=True, max_length=255, null=True)),
                ('indoor', models.CharField(blank=True, max_length=10, null=True)),
                ('invasive', models.CharField(blank=True, max_length=10, null=True)),
                ('leaf', models.CharField(blank=True, max_length=10, null=True)),
                ('maintenance', models.CharField(blank=True, max_length=255, null=True)),
                ('medicinal', models.CharField(blank=True, max_length=255, null=True)),
                ('pest_susceptibility', models.CharField(blank=True, max_length=255, null=True)),
                ('poisonous_to_humans', models.CharField(blank=True, max_length=10, null=True)),
                ('poisonous_to_pets', models.CharField(blank=True, max_length=10, null=True)),
                ('pruning_month', models.CharField(blank=True, max_length=50, null=True)),
                ('rare', models.CharField(blank=True, max_length=10, null=True)),
                ('salt_tolerant', models.CharField(blank=True, max_length=10, null=True)),
                ('soil', models.CharField(blank=True, max_length=255, null=True)),
                ('sunlight', models.TextField(blank=True, null=True)),
                ('thorny', models.CharField(blank=True, max_length=10, null=True)),
                ('tropical', models.CharField(blank=True, max_length=10, null=True)),
                ('watering', models.CharField(blank=True, max_length=50, null=True)),
                ('sun', models.CharField(blank=True, max_length=50, null=True)),
                ('edible', models.CharField(blank=True, max_length=10, null=True)),
                ('hardiness', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('watering_long', models.TextField(blank=True, null=True)),
                ('pruning', models.TextField(blank=True, null=True)),
                ('watering_period', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
