# Generated by Django 5.2.4 on 2025-12-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_like_count_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='plant_info',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='plant',
        ),
        migrations.AddField(
            model_name='post',
            name='plant_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userplant',
            name='plant_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
