# Generated by Django 5.2.4 on 2025-08-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userplant_delete_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='garden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='api.garden'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='planting_date',
            field=models.DateField(null=True),
        ),
    ]
