# Generated by Django 5.2.4 on 2025-08-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userplant_garden_alter_userplant_planting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='humidity',
            field=models.CharField(choices=[('low', 'Low humidity'), ('normal', 'Normal'), ('high', 'High humidity')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='garden',
            name='sunlight_exposure',
            field=models.CharField(choices=[('full_sun', 'Full Sun'), ('partial_sun', 'Partial Sun'), ('indirect_sun', 'Indirect Sunlight'), ('full_shade', 'Full Shade')], default='partial_sun', max_length=20),
        ),
        migrations.AlterField(
            model_name='garden',
            name='location',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='moderate', max_length=20),
        ),
    ]
