# Generated by Django 5.2.4 on 2025-12-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_post_plant_info_remove_userplant_plant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='watering_period',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
