# Generated by Django 5.2.4 on 2025-12-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userplant_watering_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
