# Generated by Django 5.2.4 on 2025-08-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_garden_humidity_garden_sunlight_exposure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='humidity',
            field=models.CharField(choices=[('low', 'Low humidity'), ('normal', 'Normal'), ('high', 'High humidity')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='garden',
            name='location',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=20),
        ),
    ]
