# Generated by Django 5.2.4 on 2025-12-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userplant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
