# Generated by Django 5.2.4 on 2025-08-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_garden_humidity_alter_garden_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='plans_info',
            field=models.ManyToManyField(blank=True, related_name='gardens', to='api.plantinfo'),
        ),
    ]
