# Generated by Django 5.2.4 on 2025-08-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_garden_plans_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='plans_info',
        ),
        migrations.AddField(
            model_name='garden',
            name='user_plants',
            field=models.ManyToManyField(blank=True, related_name='gardens', to='api.userplant'),
        ),
    ]
