# Generated by Django 5.2.4 on 2025-12-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userplant_common_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplant',
            name='isPruningReminder',
        ),
        migrations.AddField(
            model_name='userplant',
            name='fertilizing_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='fertilizing_time_unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10, null=True),
        ),
    ]
