# Generated by Django 5.2.4 on 2025-08-11 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_garden_plans_info_garden_user_plants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='user_plants',
        ),
        migrations.AlterField(
            model_name='userplant',
            name='garden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_plants', to='api.garden'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plant', to='api.plantinfo'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='planting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
