# Generated by Django 4.2.23 on 2025-12-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_userplant_ispruningreminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
