# Generated by Django 4.2.27 on 2026-01-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userplant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='userplants/'),
        ),
    ]
