# Generated by Django 5.2.4 on 2025-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_garden_user_plants_alter_userplant_garden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='age',
            field=models.CharField(blank=True, choices=[('less_1_year', 'Less than 1 year'), ('2_3_years', '2-3 years'), ('more_3_years', 'More than 3 years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='drainage',
            field=models.CharField(blank=True, choices=[('with_holes', 'With holes'), ('without_holes', 'Without holes')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='pot_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='pot_type',
            field=models.CharField(blank=True, choices=[('clay', 'Clay'), ('plastic', 'Plastic'), ('glazed_ceramic', 'Glazed ceramic/porcelain pot'), ('cement', 'Cement'), ('peat', 'Peat'), ('stone', 'Stone'), ('wood', 'Wood'), ('fabric', 'Fabric')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='pruning_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='pruning_time_unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='rotation_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='rotation_unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='sprayed_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='sprayed_unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10, null=True),
        ),
    ]
