# Generated by Django 5.2.4 on 2025-08-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userplant_age_userplant_custom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
