# Generated by Django 5.2.4 on 2025-08-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userplant_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='air',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
