# Generated by Django 4.2.27 on 2026-01-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comment_deleted_at_comment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='watering_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='watering_type',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('manual', 'Manual')], default='recommended', max_length=20),
        ),
        migrations.AddField(
            model_name='userplant',
            name='watering_unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10, null=True),
        ),
    ]
