# Generated by Django 5.2.4 on 2025-08-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_garden_air'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='isPruningReminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='isWateringReminder',
            field=models.BooleanField(default=True),
        ),
    ]
