# Generated by Django 4.2.23 on 2026-01-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userplant_watering_time_userplant_watering_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plant_common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
