# Generated by Django 5.2.4 on 2025-08-16 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userplant_ispruningreminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
