# Generated by Django 4.2.23 on 2026-01-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_post_plant_common_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
