# Generated by Django 5.2.4 on 2025-08-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userplant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='last_fertilized_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='last_pruning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='last_rotating_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='last_spraying_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
