# Generated by Django 4.2.23 on 2026-01-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_garden_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='gardens/'),
        ),
    ]
