# Generated by Django 4.2.23 on 2025-09-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userplant_last_fertilized_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantinfo',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
