# Generated by Django 4.2.27 on 2026-01-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_plantinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userplants/'),
        ),
    ]
