# Generated by Django 4.2.27 on 2026-01-13 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_alter_userplant_garden_alter_userplant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_plants', to='api.garden'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL),
        ),
    ]
