# Generated by Django 4.2.27 on 2026-01-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_userplant_garden_alter_userplant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_plants', to='api.garden'),
        ),
    ]
